spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    jdbcUrl: jdbc:sqlserver://localhost;integratedSecurity=false;
    databaseName: profee
    username: suyash
    password: sushandro

zuul:
  prefix: /api
  routes:
    feedback:
      url: http://localhost:1000/api/feedback
    product:
      url: http://localhost:2000/api/product
