spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    jdbcUrl: jdbc:sqlserver://192.168.29.97;integratedSecurity=false;
    databaseName: profee
    username: suyash
    password: sushandro
  application:
    name: profee.app

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.29.97:5000/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    feedback:
      path: /api/feedback/**
      stripPrefix: false
      serviceId: profee.feedback
    product:
      path: /api/product/**
      stripPrefix: false
      serviceId: profee.product
