CREATE TABLE Product(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name NVARCHAR(MAX) NOT NULL,
Price INT NOT NULL
);
GO

CREATE TABLE Feedback(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Title NVARCHAR(MAX) NOT NULL,
Content NVARCHAR(MAX) NOT NULL,
ProductId INT NOT NULL,
Rating INT NOT NULL,
GivenBy NVARCHAR(128) NOT NULL,
GivenOn DATE NOT NULL
)
GO
