spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    jdbcUrl: jdbc:sqlserver://localhost;integratedSecurity=false;
    databaseName: profee
    username: suyash
    password: sushandro
  application:
    name: profee.product

server:
  port: 2000


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5000/eureka}
  instance:
    preferIpAddress: true